# Generated by Django 5.0.7 on 2024-07-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='bio',
            field=models.TextField(verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='date_birth',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de cumpleaños'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
